import Button from '~/components/Button';
import HeaderPopper from '~/components/Popper/HeaderPopper';

function Home() {
    return (
        <div>
            <h2 style={{ color: 'white' }}>Home</h2>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>Home</Button>
            </HeaderPopper>
        </div>
    );
}

export default Home;
