import Button from '~/components/Button';
import HeaderPopper from '~/components/Popper/HeaderPopper';

function Search() {
    return (
        <div>
            <h2 style={{ color: 'white' }}>Search</h2>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
            <HeaderPopper>
                <Button>search</Button>
            </HeaderPopper>
        </div>
    );
}

export default Search;
